-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HR_SABAREESH
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HR_SABAREESH
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HR_SABAREESH` DEFAULT CHARACTER SET utf8 ;
USE `HR_SABAREESH` ;

-- -----------------------------------------------------
-- Table `HR_SABAREESH`.`OFFICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HR_SABAREESH`.`OFFICES` (
  `OFFICE_ID` INT NOT NULL AUTO_INCREMENT,
  `OFFICE_NAME` VARCHAR(30) NOT NULL,
  `OFFICE_ADDRESS` VARCHAR(100) NOT NULL,
  `OFFICE_CITY` VARCHAR(15) NOT NULL,
  `OFFICE_STATE` CHAR(2) NOT NULL,
  PRIMARY KEY (`OFFICE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HR_SABAREESH`.`EMPLOYEES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HR_SABAREESH`.`EMPLOYEES` (
  `Employee_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(30) NOT NULL,
  `LAST_NAME` VARCHAR(30) NOT NULL,
  `GENDER` CHAR(2) NOT NULL,
  `JOB_TITLE` VARCHAR(40) NOT NULL,
  `DURATION_MONTHS` CHAR(3) NOT NULL,
  `SALARY` VARCHAR(15) NOT NULL,
  `MANAGER_ID` INT NULL DEFAULT 'DEFAULT NULL',
  `OFFICE_ID` INT NOT NULL,
  PRIMARY KEY (`Employee_ID`),
  INDEX `FK_MANAGER_ID_idx` (`MANAGER_ID` ASC) VISIBLE,
  INDEX `FK_OFFICE_ID_idx` (`OFFICE_ID` ASC) VISIBLE,
  CONSTRAINT `FK_MANAGER_ID`
    FOREIGN KEY (`MANAGER_ID`)
    REFERENCES `HR_SABAREESH`.`EMPLOYEES` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OFFICE_ID`
    FOREIGN KEY (`OFFICE_ID`)
    REFERENCES `HR_SABAREESH`.`OFFICES` (`OFFICE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
