-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema STORE_DB_NAZEER_HW
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema STORE_DB_NAZEER_HW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `STORE_DB_NAZEER_HW` DEFAULT CHARACTER SET utf8 ;
USE `STORE_DB_NAZEER_HW` ;

-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`CUSTOMERS` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` CHAR(20) NOT NULL,
  `LAST_NAME` CHAR(20) NOT NULL,
  `GENDER` ENUM("M", "F") NOT NULL,
  `BIRTH_DATE` DATE NULL DEFAULT NULL,
  `PHONE` CHAR(10) NULL DEFAULT NULL,
  `ADDRESS` CHAR(30) NOT NULL,
  `CITY` VARCHAR(15) NOT NULL,
  `STATE` CHAR(2) NOT NULL,
  `POINTS` SMALLINT(20) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`ORDER_STATUSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`ORDER_STATUSES` (
  `ORDER_STATUSES_ID` INT NOT NULL,
  `ORDER_STATUSUS_NAME` CHAR(10) NOT NULL,
  PRIMARY KEY (`ORDER_STATUSES_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`SHIPPER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`SHIPPER` (
  `SHIPPER_ID` INT NOT NULL DEFAULT AUTO INCREMENT,
  `SHIPPER_NAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`SHIPPER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`ORDERS` (
  `ORDER_ID` INT NOT NULL DEFAULT AUTO INCREMENT IS GIVEN,
  `CUSTOMER_ID` INT NOT NULL,
  `ORDER_DATE` DATE NOT NULL,
  `STATUS` INT NOT NULL,
  `COMMENTS` VARCHAR(30) NULL DEFAULT NULL,
  `SHIPPED_DATE` DATE NULL DEFAULT NULL,
  `SHIPPER_ID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `FK_CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `FK_STATUS_idx` (`STATUS` ASC) VISIBLE,
  INDEX `FK_SHIPPER_ID_idx` (`SHIPPER_ID` ASC) VISIBLE,
  CONSTRAINT `FK_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `STORE_DB_NAZEER_HW`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_STATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `STORE_DB_NAZEER_HW`.`ORDER_STATUSES` (`ORDER_STATUSES_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SHIPPER_ID`
    FOREIGN KEY (`SHIPPER_ID`)
    REFERENCES `STORE_DB_NAZEER_HW`.`SHIPPER` (`SHIPPER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`PRODUCTS` (
  `PRODUCT_ID` INT NOT NULL DEFAULT AUTO INCREMENT,
  `PRODUCT_NAME` VARCHAR(35) NOT NULL,
  `QUANTITY_IN_STOCK` NCHAR(3) NOT NULL,
  `COST_PRICE` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `STORE_DB_NAZEER_HW`.`ORDER_ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `STORE_DB_NAZEER_HW`.`ORDER_ITEMS` (
  `ORDER_ID` INT NOT NULL DEFAULT FOREIGN KEY,
  `PRODUCT_ID` INT NOT NULL DEFAULT FOREIGN KEY,
  `QUANTITY` NCHAR(10) NOT NULL,
  `UNIT_PRICE` NCHAR(10) NOT NULL,
  INDEX `FK_ORDER_ID_idx` (`ORDER_ID` ASC) VISIBLE,
  INDEX `FK_PRODUCT_ID_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `FK_ORDER_ID`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `STORE_DB_NAZEER_HW`.`ORDERS` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PRODUCT_ID`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `STORE_DB_NAZEER_HW`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
